name: NanoSplicer
channels:
  - bioconda
  - default
dependencies:
  - python=3.7 
  - psutil
  - pandas
  - pysam
  - numpy
  - tqdm
  - h5py
  - matplotlib
  - intervaltree
  - scipy
  - scikit-image
  - pip
  - pip:
    - ont_fast5_api
    - tables
